apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "assignment.secretproviderclass" . }}
  
spec:
  provider: vault 
  {{- if .Values.env.create }}                            
  secretObjects:                             
    - secretName: foosecret
      type: Opaque     
      data:
        - key: username 
          objectName: db-password            
  {{- end }}                         
  parameters:
    vaultAddress: "http://52.249.58.138:8200"
    roleName: "database"
    objects: |
      - objectName: "db-password"
        secretPath: "/v1/secret/data/db-pass"
        secretKey: "password"
  